services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB:   world_facts
      POSTGRES_USER: ryszard
      POSTGRES_PASSWORD: KALISZ
    
    volumes:
      - ./database/import.sh:/docker-entrypoint-initdb.d/import.sh:ro
      - ./database/data.csv:/docker-entrypoint-initdb.d/data.csv:ro
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      
      DATABASE_URL: "postgres://ryszard:KALISZ@db:5432/world_facts?schema=public"
      NODE_ENV:    production
    ports:
      - "3000:3000"
    
    restart: on-failure
